name: bus
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  ionicons: ^0.1.2
  time_picker_sheet: ^0.0.2+1
  time_pickerr: ^1.0.6
  image_picker: ^0.8.5+3
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  email_validator: ^2.0.1
  flutter_svg: ^1.1.1+1
  fl_chart: ^0.55.0
  data_table_2: ^2.3.5
  numberpicker: ^2.1.1
  photo_view: ^0.14.0
  http: ^0.13.4
  path_provider: ^2.0.11
  http_parser: ^4.0.1
  path: ^1.8.1
  date_time_picker: ^2.1.0
  time_picker: ^0.0.2
  intl: ^0.17.0
  lottie: ^1.4.0
  curved_navigation_bar: ^1.0.3
  animated_card: ^2.0.0
  flutter_zoom_drawer: ^3.0.3
  animated_splash_screen: ^1.3.0
  animated_onboarding_ns: ^0.0.2
  onboarding_animation: ^0.0.1
  enhance_stepper: ^0.1.1
  qr_flutter: ^4.0.0
  iconsax: ^0.0.8
  unicons: ^2.1.0
  animated_snack_bar: ^0.2.2
  internet_connection_checker: ^0.0.1+4
  device_preview: ^1.1.0
  barcode_scan2: ^4.2.1 # permission_handler: ^10.0.0
  cool_alert: ^1.1.0
  url_launcher: ^6.1.5
  cached_network_image: ^3.2.1
  smooth_page_indicator: ^1.0.0+2
  flutter_sizer: ^1.0.5
  flutter_snake_navigationbar: ^0.6.1
  expandable_text: ^2.3.0
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  auto_size_text: ^3.0.0
  splash_screen_view: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/infinity.jpg'
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/bus.jpg
    - assets/images/person.jpg
    - assets/images/zeyad.jpeg
    - assets/images/placeholder.png
    - assets/images/error.png
    - assets/images/qrcode.json
    - assets/images/location1.json
    - assets/images/location2.json
    - assets/images/location3.json
    - assets/images/empty.json
    - assets/images/stop.png
    - assets/images/post.png
    - assets/images/backlogo.png
    - assets/images/red1.jpg
    - assets/images/overlay1.png
    - assets/images/overlay2.png
    - assets/images/overlay3.png
    - assets/images/overlay4.png
    - assets/images/background3.png
    - assets/images/background4.png
    - assets/images/add.png
    - assets/images/write.png
    - assets/images/top.png    
    - assets/images/support.json
    - assets/images/qrscanner.json
    - assets/images/bus.json
    - assets/images/erorr.json
    - assets/images/user.json
    - assets/images/money.json
    - assets/images/busstop.svg
    - assets/images/nowifi.json
    - assets/images/nowifi2.json

    - assets/images/infinity.jpg

    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        # - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: OleoScriptSwashCaps
      fonts:
        - asset: assets/fonts/OleoScriptSwashCaps-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: RaleWay
      fonts:
        - asset: assets/fonts/Raleway-VariableFont_wght.ttf
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-VariableFont_wght.ttf
    - family: Uchen
      fonts:
        - asset: assets/fonts/Uchen-Regular.ttf

  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
